version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ring76-php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    restart: always
